### PR TITLE
Added Fire Charge Torch Recipe and Various Bug Fixes

### PR DESCRIPTION
**Pull request by Dariensg**
-Fire Charge and stick in crafting makes 12 torches

### CODE REVIEW

**Comment by Dariensg** [comment]
-Fixed Pig/Hoglin loot being shared
-Burning Hoglins now drop cooked hogchops

**Comment by Dariensg** [comment]
-Glowspikes should no longer spawn above bedrock

**Comment by caelwarner** [comment]
I'm just curious, what's the need for having the loot table modifier in java code and in json files? I thought it could all be done through json

**Comment by Dariensg** [comment]
I believe it’s just in Json if you just overwrite the loot table, which we don’t necessarily want to do. This method allows us to simply modify parts of the drops without having to rewrite and override the entire loot table.

**Review by SwanX1 — APPROVED** [review]

**Pull request merged**
