### PR TITLE
Throwable brick & Plantable Quartz

### PR DESCRIPTION
**Pull request by SwanX1**

### CODE REVIEW

**Review by Dariensg — APPROVED** [review]
LGTM

**Comment by nekomaster1000** [comment]
You gonna commit this, then...?

**Comment by caelwarner** [comment]
Didn't even leave a nice, in depth description of this pr. I want to know exactly what this throwable brick is, what it does, its purpose in life

**Comment by SwanX1** [comment]
> Didn't even leave a nice, in depth description of this pr. I want to know exactly what this throwable brick is, what it does, its purpose in life

it's a brick, but it's throwable

**Comment by nekomaster1000** [comment]
Things to do for this branch:
- Add impact noises when the bricks hit a target
- Make Nether Bricks fly faster than normal bricks
- Make the hitbox of the bricks less jank
and we should be good!

**Comment by SwanX1** [comment]
Closing PR for now, will reopen when relevant.

**Comment by SwanX1** [comment]
Closing this in favor a rewritten PR.

**Pull request closed without merging**
