### PR TITLE
JSON spawnrate config files

### LINKED ISSUE #47: Add config to customize mobs spawning in biomes
I looked through the server config in the world folder, and all it does is turn on and off existing features. I think it could be cool to allow adding biomes that the mobs can spawn in. This works nicely because then if people like me have biome mods, they can add biomes for the creatures to spawn in. This also could benefit modpack makers. I personally use oh the biomes you'll go and have a couple biomes I want to add to spawn listing.

### PR DESCRIPTION
**Pull request by caelwarner**
- All mobs need to be converted over to using json spawnrate config files (currently only the warpbeetle has been converted)
- After that I have to do some general cleanup (removing old config stuff)

### CODE REVIEW

**Review by SwanX1 — COMMENTED** [review]
the spawnrates should be a config, not a resource

**Comment by caelwarner** [comment]
> the spawnrates should be a config, not a resource
> 

Forge config files are too rigid for this purpose. JSON files make much more sense. And it's in the resources folder so we can use minecrafts pre-existing JSON reading code

**Comment by caelwarner** [comment]
I implore anyone else to port the spawnrates for each mob from MobEvents to JSON files. Once all mobs have been ported I will finish off this PR by doing some code cleanup (removing old mob spawnrate code)

**Review by SwanX1 — APPROVED** [review]

**Comment by SwanX1** [comment]
Blindsights don't seem to be spawning, please fix this.

**Pull request merged**
