### PR TITLE
Added spawn command for dimensions

### LINKED ISSUE #132: Using /setworldspawn in the Nether works like the overworld where it permanently sets your spawn without the need for a respawn anchor
being able to /setworldspawn in the Nether and it permanently setting your spawn would be great for true nether survivals without constantly recharging your respawn anchor.

### PR DESCRIPTION
**Pull request by Dariensg**
-Added setdimensionspawn which allows each player to set their spawnpoint in any dimension, not just the overworld. This is where you will spawn no matter what dimension you die in, it is not specific to dying in that dimension
-Fixed broken lang files
-Synced all lang files up with en_us once more

### CODE REVIEW

**Review by SwanX1 — CHANGES_REQUESTED** [review]
The command should be able to affect other players, not only the same player.
Also, why are you registering the command twice, in line 24 and 38?
Minor syntax issue: `// Comments should have a space after the slashes.`

**Comment by Dariensg** [comment]
By affect other players do you mean take in a player as input? If so, I didn't think about that, but I'll make the change.
As far as the double register, I just copied the method that ntp uses for registering the command. It does the same thing.
I'll fix the syntax issue in my player input commit.

**Review by SwanX1 — CHANGES_REQUESTED** [review]
You still haven't fixed the duplicate registering of the command in lines 28 and 60 in `src/main/java/com/nekomaster1000/infernalexp/init/IECommands.java`

**Comment by Dariensg** [comment]
NTP does the same thing. Is that not necessary in some way and should we get rid of it in NTP?

**Comment by SwanX1** [comment]
>> You still haven't fixed the duplicate registering of the command in lines 28 and 60 in `src/main/java/com/nekomaster1000/infernalexp/init/IECommands.java`

> NTP does the same thing. Is that not necessary in some way and should we get rid of it in NTP?

Yes, I believe so. there is no point in registering it twice (the second time just redirecting to the first registration)

**Pull request merged**
